ja:
  home: "ホームページ"
  version: "2014 版権所有"
  policy: "プライバシーポリシー"   
  tos: "サービス条項"
  about: "について"
  feedback: "フィードバック"
  user:
    admin: "管理"
    profile: "個人情報"
    logout: "消却"
    signup: "登録"
    signin: "サインイン"
    login: "ユーザーまたはメールアドレス"
    password: "パスワード"
    confirmpassword: "パスワードの確認"
    currentpassword: "現在のパスワード"   
    currentpasswordhint: "現在のパスワードを入力して、変更情報を確認する"
    username: "ユーザー"　　　　
    email: "メールアドレス"
    teacher: "私は先生になり、コースをアップする"　　　
    invitation_token: "招待コード"
  videos:
    new: "新しいコース"
    browse: "閲覧コース"　　　　
    tech: "技術の分類"　　　　
    filename: "コースの名称"　　　
    still: "コース选択してアップして"　　　　
    description: "授業内容の説明"
    descriptionhint: "本コース関連の内容概要を詳細を入力してください"　　　　
    tags: "技術の分類"　　　　　
    tagshint: "使用コンマ（、）別の分類"
    publishedhint: "コースを今すぐに公表する"　　
    cancel: "キャンセル"　　　　
    upload: "コースをアップする"　　　
    edit: "編集"　　　
    delete: "デリート"　　　
    confirm: "確定か?"　　 
    watch: "観覧コース"　　
  welcome:
    title: "诩阆"
    title1: "诩"
    title2: "阆"
    home: "ホームページ"
    about: "愿景"
    course: "コース"　　
    features: "機能"　　　
    join: "加入"
    inviteme: "私を誘ってください"
    email: "Eメールアドレス"　　　　
    iwantbeenginner: "私は立派なエンジニアになりたい"
    iwantin: "私は参与し"　　　
    weareat: "今はまだ"　　　
    beta: "よい"　　
    dev: "版の初期開発段階"
    leaveemail: "留下您的Email地址，网站正式发布上线后，我们会邮件邀请您参与。"
    slider:
      why: "我们的课程由专业的工程师团队精心打造"
      learn: "您有您的梦想，我们为您的梦想革新,"
      pratice: "助您成为智才，且企业人尽其才！"
      about: "我们的愿景和使命"
      want: "我们深知传统教育纸上谈兵的不足,深知企业对优秀技术工程师的渴求."
      new: "工业在革新，工程师发展之路也才革新！"
      mission: "我们为您提供专业精确的技术职业发展路线，帮助你快速的学习，提升实际工业工作的能力，为企业培训休秀的工程师。"
      quotes: "如果你愿意提升自己,你可以提升任何事情."
      revelution: "我们在做别人没有做过的事情，我们在革新工程师的教育。"
      goodengineer: "我们将帮助您实现成为优秀工程师的梦想,"
      face: "我们将革新工程师教育的全新面貌。"
      team: "我们有一支专业的工程师团队。"
      teamdesc: "我们都有在工业领域工作的经验,制作满足于企业需求的工程师培训课程。"
      student: "从学生到工程师"
      studentdev: "为您铺就一条从学校到企业，从学生到技术工程师的道路，通过培训，弥补学校传统教育与现实企业间的差距，让您快速的进入工程师的角色。"
      technician: "从技术员到工程师"
      techniciandev: "为您打开工程师培训之路，抛开企业的培训体系限制，快速的通过培训，提升自己的能力，从技术员跨越到工业师"
      engineer: "工程师的自我修养"
      engineerdev: "一个优秀的工程师，总停不下学习之路，通过自主的学习，提升自己的能力，保持最新的技术状态，在新的挑战之下游刃有余。"
      course: "我们的课程"
      course1: "我们制作的应用型培训课程, 由易到难，帮助您迅速掌握每一门技术各个环节的精髓，"
      course2: "并迅速应用至实际工作。学习内容可弹性扩张，自由选择."   
  course:
    technology: "技术分类"
    keyword: "关键字"
    soft: "第三方软件"
    app: "原生app"
    robotics: "机器人技术"
    electric: "电器工程技术"
    robotguide: "Roboguide"
    mechanic: "机械制造技术"
    rapid: "RAPID 开发"
    onsitetask: "工程师现场工作"
    val3: "VAL3"
    plc: "PLC"
    kal: "KAL"
    traceability: "追溯系统开发"
    fieldbus: "现场总线"
    siemens: "Siemens PLC"
    ab: "AB PLC"
    vision: "机器人视觉"
    lasercutting: "激光切割"
    grinding: "打磨"